spring.application.name=apipalavras

#JPA
spring.jpa.show-sql=true
spring.profiles.active=local

spring.datasource.url=jdbc:mysql://localhost:3306/bancoapi/${DB_NAME:bancoapi}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

spring.security.user.name=admin
spring.security.user.password=m1nh4s3nh4!!

#FLYWAY
spring.flyway.locations=classpath:db/migration


